version: '3.7'

services:

  db:
    image: postgres:17.4
    restart: always
    container_name: fitnycrm-db
    shm_size: '256mb'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ~/data/docker/fitnycrm/db:/var/lib/postgresql/data:delegated